Added DH publish Added GHCR publish

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,10 +38,58 @@ jobs:
       with:
         message: 'Updated the remote panel (stable)'
         branch: master
+  workflowvars:
+    name: Setup Workflow Vars
+    runs-on: ubuntu-latest
+    outputs:
+      dockermissing: ${{ steps.check_docker_credentials.outputs.missingsecrets }}
+      rollbarmissing: ${{ steps.check_rollbar_credentials.outputs.missingsecrets }}
+      branch: ${{ steps.build_env.outputs.branch }}
+      version: ${{ steps.build_env.outputs.version }}
+      revision: ${{ steps.build_env.outputs.revision }}
+    steps:
+    - name: Get Revision Variables
+      id: build_env
+      run: |
+        echo "##[set-output name=branch;]$(echo ${GITHUB_REF:10})"
+        echo "##[set-output name=version;]$(echo ${GITHUB_REF:11})"
+        echo "##[set-output name=revision;]$(echo ${GITHUB_SHA:0:7})"
+    - name: Check Docker Credentials
+      id: check_docker_credentials
+      env:
+        DOCKER_USER: ${{ secrets.DOCKER_USER }}
+        DOCKER_CLITOKEN: ${{ secrets.DOCKER_CLITOKEN }}
+        DOCKER_REPO_STABLE: ${{ secrets.DOCKER_REPO_STABLE }}
+      run: |
+        if [ "${DOCKER_USER}" == "" ]; then
+          echo "Missing User"
+          echo "##[set-output name=missingsecrets;]$(echo yes)"
+        elif [ "${DOCKER_CLITOKEN}" == "" ]; then
+          echo "Missing Cli Token"
+          echo "##[set-output name=missingsecrets;]$(echo yes)"
+        elif [ "${DOCKER_REPO_STABLE}" == "" ]; then
+          echo "Missing Repo"
+          echo "##[set-output name=missingsecrets;]$(echo yes)"
+        else
+          echo "All secrets present"
+          echo "##[set-output name=missingsecrets;]$(echo no)"
+        fi
+    - name: Check Rollbar Credentials
+      id: check_rollbar_credentials
+      env:
+        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_WRITE_TOKEN }}
+      run: |
+        if [ "${ROLLBAR_ACCESS_TOKEN}" == "" ]; then
+          echo "Missing Rollbar Access Token"
+          echo "##[set-output name=missingsecrets;]$(echo yes)"
+        else
+          echo "All secrets present"
+          echo "##[set-output name=missingsecrets;]$(echo no)"
+        fi
   build:
     name: Build and upload on ubuntu-latest with JDK 11.0.11
     runs-on: ubuntu-latest
-    needs: buildtest
+    needs: [buildtest, workflowvars]
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
@@ -52,26 +100,21 @@ jobs:
         java-version: 11.0.11
     - name: Set up Ant
       run: sudo apt-get install ant
-    - name: Set up environment variables
-      id: build_env
-      run: |
-        echo "##[set-output name=branch;]$(echo ${GITHUB_REF:10})"
-        echo "##[set-output name=version;]$(echo ${GITHUB_REF:11})"
-        echo "##[set-output name=revision;]$(echo ${GITHUB_SHA:0:7})"
     - name: Notify Rollbar of Deploy Start
+      if: contains(needs.workflowvars.outputs.rollbarmissing, 'no')
       id: rollbar_deploy
       uses: rollbar/github-deploy-action@2.1.1
       with:
         environment: "stable"
-        version: ${{ steps.build_env.outputs.version }}
+        version: ${{ needs.workflowvars.outputs.version }}
         status: "started"
       env:
         ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_WRITE_TOKEN }}
         ROLLBAR_USERNAME: ${{ github.actor }}
     - name: Prep Ant script
       env:
-        BRANCH: ${{ steps.build_env.outputs.branch }}
-        REVISION: ${{ steps.build_env.outputs.revision }}
+        BRANCH: ${{ needs.workflowvars.outputs.branch }}
+        REVISION: ${{ needs.workflowvars.outputs.revision }}
       run: |
         sed -i -r 's/revision="[A-Za-z0-9._-]+"/revision="'$REVISION'"/;s/branch="[A-Za-z0-9._-]+"/branch="'$BRANCH'"/;s/status="[A-Za-z0-9._-]+"/status="release"/' ivy.xml
         echo $?
@@ -82,11 +125,11 @@ jobs:
       run: ant -noinput -Dbuildtype=stable -Drollbar_token=$ROLLBAR_TOKEN -Drollbar_endpoint=$ROLLBAR_ENDPOINT -buildfile build.xml jar
     - name: Prep Assets
       env:
-        FOLDERFULL: ${{ format('PhantomBot-{0}', steps.build_env.outputs.version) }}
-        FOLDERLIN: ${{ format('PhantomBot-{0}-lin', steps.build_env.outputs.version) }}
-        FOLDERWIN: ${{ format('PhantomBot-{0}-win', steps.build_env.outputs.version) }}
-        FOLDERMAC: ${{ format('PhantomBot-{0}-mac', steps.build_env.outputs.version) }}
-        FOLDERARMBSDOTHER: ${{ format('PhantomBot-{0}-arm-bsd-other', steps.build_env.outputs.version) }}
+        FOLDERFULL: ${{ format('PhantomBot-{0}', needs.workflowvars.outputs.version) }}
+        FOLDERLIN: ${{ format('PhantomBot-{0}-lin', needs.workflowvars.outputs.version) }}
+        FOLDERWIN: ${{ format('PhantomBot-{0}-win', needs.workflowvars.outputs.version) }}
+        FOLDERMAC: ${{ format('PhantomBot-{0}-mac', needs.workflowvars.outputs.version) }}
+        FOLDERARMBSDOTHER: ${{ format('PhantomBot-{0}-arm-bsd-other', needs.workflowvars.outputs.version) }}
       run: |
         mkdir dist/$FOLDERLIN
         rsync -rav --progress dist/$FOLDERFULL dist/$FOLDERLIN --exclude java-runtime --exclude java-runtime-macos --exclude launch.bat --exclude launch-bsd.sh --exclude launch-bsd-service.sh --exclude launch-docker.sh
@@ -133,8 +176,8 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ github.event.release.upload_url }}
-        asset_path: ${{ format('dist/PhantomBot-{0}.zip', steps.build_env.outputs.version) }}
-        asset_name: ${{ format('PhantomBot-{0}.zip', steps.build_env.outputs.version) }}
+        asset_path: ${{ format('dist/PhantomBot-{0}.zip', needs.workflowvars.outputs.version) }}
+        asset_name: ${{ format('PhantomBot-{0}.zip', needs.workflowvars.outputs.version) }}
         asset_content_type: application/zip
     - name: Upload Asset (Linux)
       uses: actions/upload-release-asset@v1
@@ -142,8 +185,8 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ github.event.release.upload_url }}
-        asset_path: ${{ format('dist/PhantomBot-{0}-lin.zip', steps.build_env.outputs.version) }}
-        asset_name: ${{ format('PhantomBot-{0}-lin.zip', steps.build_env.outputs.version) }}
+        asset_path: ${{ format('dist/PhantomBot-{0}-lin.zip', needs.workflowvars.outputs.version) }}
+        asset_name: ${{ format('PhantomBot-{0}-lin.zip', needs.workflowvars.outputs.version) }}
         asset_content_type: application/zip
     - name: Upload Asset (Windows)
       uses: actions/upload-release-asset@v1
@@ -151,8 +194,8 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ github.event.release.upload_url }}
-        asset_path: ${{ format('dist/PhantomBot-{0}-win.zip', steps.build_env.outputs.version) }}
-        asset_name: ${{ format('PhantomBot-{0}-win.zip', steps.build_env.outputs.version) }}
+        asset_path: ${{ format('dist/PhantomBot-{0}-win.zip', needs.workflowvars.outputs.version) }}
+        asset_name: ${{ format('PhantomBot-{0}-win.zip', needs.workflowvars.outputs.version) }}
         asset_content_type: application/zip
     - name: Upload Asset (macOS)
       uses: actions/upload-release-asset@v1
@@ -160,8 +203,8 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ github.event.release.upload_url }}
-        asset_path: ${{ format('dist/PhantomBot-{0}-mac.zip', steps.build_env.outputs.version) }}
-        asset_name: ${{ format('PhantomBot-{0}-mac.zip', steps.build_env.outputs.version) }}
+        asset_path: ${{ format('dist/PhantomBot-{0}-mac.zip', needs.workflowvars.outputs.version) }}
+        asset_name: ${{ format('PhantomBot-{0}-mac.zip', needs.workflowvars.outputs.version) }}
         asset_content_type: application/zip
     - name: Upload Asset (ARM/BSD/Other)
       uses: actions/upload-release-asset@v1
@@ -169,26 +212,122 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ github.event.release.upload_url }}
-        asset_path: ${{ format('dist/PhantomBot-{0}-arm-bsd-other.zip', steps.build_env.outputs.version) }}
-        asset_name: ${{ format('PhantomBot-{0}-arm-bsd-other.zip', steps.build_env.outputs.version) }}
+        asset_path: ${{ format('dist/PhantomBot-{0}-arm-bsd-other.zip', needs.workflowvars.outputs.version) }}
+        asset_name: ${{ format('PhantomBot-{0}-arm-bsd-other.zip', needs.workflowvars.outputs.version) }}
         asset_content_type: application/zip
     - name: Notify Rollbar of Deploy Failure
-      if: ${{ failure() || cancelled() }}
+      if: ${{ contains(needs.workflowvars.outputs.rollbarmissing, 'no') && (failure() || cancelled()) }}
       uses: rollbar/github-deploy-action@2.1.1
       with:
         environment: "stable"
-        version: ${{ steps.build_env.outputs.version }}
+        version: ${{ needs.workflowvars.outputs.version }}
         status: "failed"
       env:
         ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_WRITE_TOKEN }}
         ROLLBAR_USERNAME: ${{ github.actor }}
         DEPLOY_ID: ${{ steps.rollbar_deploy.outputs.deploy_id }}
     - name: Notify Rollbar of Deploy Success
-      if: ${{ success() }}
+      if: ${{ contains(needs.workflowvars.outputs.rollbarmissing, 'no') && success() }}
       uses: rollbar/github-deploy-action@2.1.1
       with:
         environment: "stable"
-        version: ${{ steps.build_env.outputs.version }}
+        version: ${{ needs.workflowvars.outputs.version }}
+        status: "succeeded"
+      env:
+        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_WRITE_TOKEN }}
+        ROLLBAR_USERNAME: ${{ github.actor }}
+        DEPLOY_ID: ${{ steps.rollbar_deploy.outputs.deploy_id }}
+  docker:
+    name: Docker build on ubuntu-latest with JDK 11.0.11
+    runs-on: ubuntu-latest
+    needs: [buildtest, workflowvars]
+    steps:
+    - name: Checkout Repository
+      uses: actions/checkout@v2
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v1
+      with:
+        platforms: linux/amd64,linux/arm64,linux/arm/v7
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v1
+      with:
+        version: latest
+    - name: Login to DockerHub Registry
+      if: contains(needs.workflowvars.outputs.dockermissing, 'no')
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKER_USER }}
+        password: ${{ secrets.DOCKER_CLITOKEN }}
+        logout: true
+    - name: Login to GitHub Container Registry
+      uses: docker/login-action@v1
+      with:
+        registry: ghcr.io
+        username: ${{ github.repository_owner }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+        logout: true
+    - name: Notify Rollbar of Deploy Start
+      if: contains(needs.workflowvars.outputs.rollbarmissing, 'no')
+      id: rollbar_deploy
+      uses: rollbar/github-deploy-action@2.1.1
+      with:
+        environment: "stable_docker"
+        version: ${{ needs.workflowvars.outputs.version }}
+        status: "started"
+      env:
+        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_WRITE_TOKEN }}
+        ROLLBAR_USERNAME: ${{ github.actor }}
+    - name: Prep Ant script
+      env:
+        BRANCH: ${{ needs.workflowvars.outputs.branch }}
+        REVISION: ${{ needs.workflowvars.outputs.revision }}
+      run: |
+        sed -i -r 's/revision="[A-Za-z0-9._-]+"/revision="'$REVISION'"/;s/branch="[A-Za-z0-9._-]+"/branch="'$BRANCH'"/;s/status="[A-Za-z0-9._-]+"/status="release"/' ivy.xml
+        echo $?
+    - name: Build and Push DockerHub
+      if: contains(needs.workflowvars.outputs.dockermissing, 'no')
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        file: ./Dockerfile
+        platforms: linux/amd64,linux/arm64,linux/arm/v7
+        push: true
+        build-args: |
+          PROJECT_VERSION=${{ needs.workflowvars.outputs.version }}
+          ANT_ARGS="-Dbuildtype=stable -Drollbar_token=${{ secrets.ROLLBAR_TOKEN }} -Drollbar_endpoint=${{ secrets.ROLLBAR_ENDPOINT }}"
+        tags: |
+          ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO_STABLE }}:${{ needs.workflowvars.outputs.version }}
+          ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO_STABLE }}:latest
+    - name: Build and Push GitHub Containers
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        file: ./Dockerfile
+        platforms: linux/amd64,linux/arm64,linux/arm/v7
+        push: true
+        build-args: |
+          PROJECT_VERSION=${{ needs.workflowvars.outputs.version }}
+          ANT_ARGS="-Dbuildtype=stable -Drollbar_token=${{ secrets.ROLLBAR_TOKEN }} -Drollbar_endpoint=${{ secrets.ROLLBAR_ENDPOINT }}"
+        tags: |
+          ghcr.io/${{ github.repository }}:${{ needs.workflowvars.outputs.version }}
+          ghcr.io/${{ github.repository }}:latest
+    - name: Notify Rollbar of Deploy Failure
+      if: ${{ contains(needs.workflowvars.outputs.rollbarmissing, 'no') && (failure() || cancelled()) }}
+      uses: rollbar/github-deploy-action@2.1.1
+      with:
+        environment: "stable_docker"
+        version: ${{ needs.workflowvars.outputs.version }}
+        status: "failed"
+      env:
+        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_WRITE_TOKEN }}
+        ROLLBAR_USERNAME: ${{ github.actor }}
+        DEPLOY_ID: ${{ steps.rollbar_deploy.outputs.deploy_id }}
+    - name: Notify Rollbar of Deploy Success
+      if: ${{ contains(needs.workflowvars.outputs.rollbarmissing, 'no') && success() }}
+      uses: rollbar/github-deploy-action@2.1.1
+      with:
+        environment: "stable_docker"
+        version: ${{ needs.workflowvars.outputs.version }}
         status: "succeeded"
       env:
         ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_WRITE_TOKEN }}
